"""Create tag_archetype_lemmas association table

Revision ID: 0369b2cf253a
Revises: 4c3e15d3267f
Create Date: 2025-10-02 22:06:43.668351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0369b2cf253a'
down_revision: Union[str, Sequence[str], None] = '4c3e15d3267f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_archetype_lemmas',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('lemma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lemma_id'], ['verb_lemmas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'lemma_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_archetype_lemmas')
    # ### end Alembic commands ###
