"""Create initial database schema from final models

Revision ID: 4c3e15d3267f
Revises: 
Create Date: 2025-10-02 21:40:05.987260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c3e15d3267f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_hacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RULE', 'MNEMONIC', 'CONSTRUCTION', 'PATTERN', 'DISTINCTION', 'CONNECTOR', name='hack_type_enum'), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('example_front', sa.Text(), nullable=False),
    sa.Column('example_back', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_hacks_name'), 'learning_hacks', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), nullable=False),
    sa.Column('visibility', sa.Enum('INTERNAL', 'BETA', 'PUBLIC', name='visibility_enum'), server_default='INTERNAL', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logic_group', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('verb_lemmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verb_lemmas_lemma'), 'verb_lemmas', ['lemma'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('new', 'viewed', 'in_progress', 'resolved', 'archived', name='feedback_status'), server_default='new', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('frequent_verb_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=50), nullable=False),
    sa.Column('is_survival_essential', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tense', sa.String(length=50), nullable=True),
    sa.Column('person', sa.String(length=50), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['verb_lemmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frequent_verb_forms_lemma_id'), 'frequent_verb_forms', ['lemma_id'], unique=False)
    op.create_index(op.f('ix_frequent_verb_forms_rank'), 'frequent_verb_forms', ['rank'], unique=False)
    op.create_table('hack_to_tag_relationships',
    sa.Column('hack_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('TEACHES', 'REQUIRES', 'REMEDIATES', name='hack_tag_relationship_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['hack_id'], ['learning_hacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hack_id', 'tag_id', 'relationship_type')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('field1', sa.Text(), nullable=False),
    sa.Column('field2', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('tag_relationships',
    sa.Column('source_tag_id', sa.Integer(), nullable=False),
    sa.Column('target_tag_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PREREQUISITE', 'DEPENDENCY', 'ANALOGY', 'CO-REQUISITE', 'IS_PARENT_OF', name='tag_relationship_type_enum'), nullable=False),
    sa.Column('weight', sa.Double(precision=53), server_default='1.0', nullable=False),
    sa.ForeignKeyConstraint(['source_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_tag_id', 'target_tag_id', 'relationship_type')
    )
    op.create_table('user_awards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_review_day', sa.Date(), nullable=True),
    sa.Column('reviews_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_last_updated_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_tag_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Double(precision=53), server_default='0.0', nullable=False),
    sa.Column('opportunity_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hard_grades_on_success', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_successes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_five_outcomes', sa.ARRAY(sa.Boolean()), server_default='{}', nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapse_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pedagogical_difficulty', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_note_id'), 'cards', ['note_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('review_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('pre_review_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('post_review_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_log')
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_cards_note_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('user_tag_scores')
    op.drop_table('user_awards')
    op.drop_table('tag_relationships')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.drop_table('notes')
    op.drop_table('hack_to_tag_relationships')
    op.drop_index(op.f('ix_frequent_verb_forms_rank'), table_name='frequent_verb_forms')
    op.drop_index(op.f('ix_frequent_verb_forms_lemma_id'), table_name='frequent_verb_forms')
    op.drop_table('frequent_verb_forms')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_verb_lemmas_lemma'), table_name='verb_lemmas')
    op.drop_table('verb_lemmas')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_learning_hacks_name'), table_name='learning_hacks')
    op.drop_table('learning_hacks')
    # ### end Alembic commands ###
