"""add_suspended_column_to_cards

Revision ID: 51f4ce7611d3
Revises: 5d71e890dd06
Create Date: 2026-03-17 10:32:24.236886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f4ce7611d3'
down_revision: Union[str, Sequence[str], None] = '5d71e890dd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.TEXT(), server_default=sa.text("'Europe/Madrid'::text"), autoincrement=False, nullable=False, comment='timezone of user'))
    op.drop_column('cards', 'suspended')
    # ### end Alembic commands ###
