"""Correct ENUM values for tag_relationship_type

Revision ID: 5d71e890dd06
Revises: 0369b2cf253a
Create Date: 2025-10-02 22:15:20.751846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d71e890dd06'
down_revision: Union[str, Sequence[str], None] = '0369b2cf253a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
