"""Add daily review count to user awards

Revision ID: 9c7269a56e96
Revises: 0614a63d87ba
Create Date: 2025-08-19 15:07:16.005053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7269a56e96'
down_revision: Union[str, Sequence[str], None] = '0614a63d87ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_awards', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('user_awards', sa.Column('daily_review_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('user_awards', 'last_review_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_awards', sa.Column('last_review_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_awards', 'daily_review_count')
    op.drop_column('user_awards', 'last_activity_date')
    # ### end Alembic commands ###
