"""Add review count and streak date columns to user_awards

Revision ID: bf995b6bca58
Revises: 9c7269a56e96
Create Date: 2025-08-20 16:48:41.113603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf995b6bca58'
down_revision: Union[str, Sequence[str], None] = '9c7269a56e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_awards', sa.Column('current_review_date', sa.Date(), nullable=True))
    op.add_column('user_awards', sa.Column('current_review_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_awards', sa.Column('streak_last_updated_date', sa.Date(), nullable=True))
    op.drop_column('user_awards', 'last_activity_date')
    op.drop_column('user_awards', 'daily_review_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_awards', sa.Column('daily_review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('user_awards', sa.Column('last_activity_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_awards', 'streak_last_updated_date')
    op.drop_column('user_awards', 'current_review_count')
    op.drop_column('user_awards', 'current_review_date')
    # ### end Alembic commands ###
